### ISSUE TITLE
Publish plugin on Marketplace

### ISSUE THREAD

**Issue by sgiehl** [matomo-org/plugin-CustomVariables#2]
With Matomo 4 Custom Variables plugin will no longer be part of the core. To still have it available, we need to publish the plugin to the Marketplace.

Before doing this, we need at least

* [x] Apply required changes to have the plugin independent from core (--> see #1)
* [x] Create a README file with a proper description of the plugin
* [x] Add some screenshots for the plugin
* [x] Setup the marketplace hook in this repo
* [ ] Release a new version

**Comment by tsteur** [comment]
fyi webhook is now active.

**Comment by tsteur** [comment]
Added the readme as well. Screenshots aren't needed since we are deprecating this feature anyway. Basically only need to release a new version
