### ISSUE TITLE
CustomVariablesRequestProcessor utf8mb4 support

### ISSUE THREAD

**Issue by MichaelRoosz** [matomo-org/plugin-CustomVariables#40]
I think we should replace the substr() call in CustomVariablesRequestProcessor with mb_substr() to properly cut utf8 values
https://github.com/matomo-org/plugin-CustomVariables/blob/d731ff01e095800173b89bf804d432744437b5a4/Tracker/CustomVariablesRequestProcessor.php#L138

**Comment by AltamashShaikh** [comment]
Hi @MichaelRoosz 
Thanks for the suggestion, could you may be send a PR with the suggested changes?
Ill be happy to review and get it merged.
